### ISSUE TITLE
Json syntax

### ISSUE THREAD

**Issue by mgwalm** [douglascrockford/JSON-js#115]
Im trying to understand the json systax. Your page at https://www.crockford.com/mckeeman.html says the following

json
   element

surely it should be 
json
   elements

**Comment by douglascrockford** [comment]
Surely not.

**Comment by fulldecent** [comment]
@mgwalm the grammar `elements` would allow such documents as:

```
true, true
```

And such is not (both intentionally and actually) a valid JSON.

A reference for learning more on the grammar is: https://en.wikipedia.org/wiki/Backus–Naur_form as a starting point. You will find the most help there. But that is only a start, you will need to read the actual grammar on the page you cite to be specific.

Please as questions like "Im trying to understand..." on other forums since this is not the place for that type of discussion.
