### ISSUE TITLE
BigInt support

### ISSUE THREAD

**Issue by vitaly-t** [douglascrockford/JSON-js#117]
I hope this doesn't go too far off with acceptable issue topics here, and if it does - my apologies.

---

I was looking for a solution that would support the new `BigInt` type within `JSON.stringify`, but nothing so far...

The existing implementation simply throws an error when encountering `BigInt`.

And when using a replacer function, like this one:

```js
function toJson(data) {
    return JSON.stringify(data, (_, v) => typeof v === 'bigint' ? v.toString() : v);
}
```

We end up with all `BigInt` values wrapped into double quotes instead of being an open value.

[Here's the the bigger problem that brought me here](https://stackoverflow.com/questions/58249954/json-stringify-and-postgresql-bigint-compliance).

I am hoping to find something elegant, without the need of replacing the whole `JSON.stringify`, so maybe you can offer something from your extensive experience with this?

**Comment by douglascrockford** [comment]
json2.js was intended to bridge the transition between ES3 and ES5, which it did, successfully. It is now at end of life and should no longer be used.

The problem you are encountering is using an (apparently) poorly designed proposed new language feature. I don't track the standards process any more, so I don't know if the problem is that your JS engine did not properly make matching changes to JSON methods, or if TC-39 failed to think through the consequences of their unnecessary bigint design.

I would avoid bigints until this gets sorted, if not longer. Meanwhile, send your complaints to ECMA.

**Comment by vitaly-t** [comment]
> Meanwhile, send your complaints to ECMA.

I did, and a lot more, thanks! :smile: I did come up with a usable solution there in the end. Wasn't going to sit around, brooding on the subject with ECMA guys. :smile:
