### ISSUE TITLE
json parse: get wrong result

### ISSUE THREAD

**Issue by piyongcai** [douglascrockford/JSON-js#134]
testcode:
1. have a json string :  `{"id1": 9196877626998784, "id2": 9196877626998785}` 
2.  call JSON.parse
3.  check result:  you find id2 is `9196877626998784`, it's a wrong result.

```html

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>JSON Test</title>
    <script src="json2.js" type="text/javascript"></script>
</head>
<body> 
    <script>
        let jsStr = "{\"id1\": 9196877626998784, \"id2\": 9196877626998785}"
        document.write("JSON String:<br>", jsStr ,"<br><br>")

        let xx = JSON.parse(jsStr);
        document.writeln("AFTER JSON.parse:<br> id1 = ", xx.id1,  " id2 = ", xx.id2);
    </script>
</body>
</html>

```

CHECK RESULT:
```text
JSON String:
{"id1": 9196877626998784, "id2": 9196877626998785}

AFTER JSON.parse:
id1 = 9196877626998784 id2 = 9196877626998784
```

**Comment by tmtron** [comment]
That's expected, because your integers are higher than [MAX_SAFE_INTEGER](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/MAX_SAFE_INTEGER). And [json](https://www.json.org/) does not support bigint.

When you want to transfer bigints, you should send them as string: e.g. `9196877626998785`.  
Or search for "JSON bigint" to find other workaournds: i.e. https://stackoverflow.com/questions/18755125/node-js-is-there-any-proper-way-to-parse-json-with-large-numbers-long-bigin

**Comment by piyongcai** [comment]
@tmtron thanks.
