### ISSUE TITLE
JSON.decycle() does not preserve functions within objects

### ISSUE THREAD

**Issue by loglot** [douglascrockford/JSON-js#139]
i'm making objects like this
```javascript
import { Item } from "item.js"

var list = []
var list[0] = new Item("text info", function func(/* required code */))
var listBak = JSON.stringify(JSON.decycle(list))
list = JSON.retrocycle(JSON.parse(listBak))
console.log(list)
```
Item being a class that has the variables `Text` and `Func`. the log would return `[{"Text":"text info"}]` when it should return `[{"Text":"text info", Func: /* function info */}]`

**Comment by nxpatterns** [comment]
`JSON.stringify` won't serialise functions. Since the `Func` property is a function, it gets lost during serialisation and deserialisation and that's the normal behaviour. 

Try this one:

```js
// Custom decycle and retrocycle
function decycleWithFuncs(obj) {
    return JSON.stringify(obj, (key, value) => {
        if (typeof value === 'function') {
            return value.toString();
        }
        return value;
    });
}

function retrocycleWithFuncs(json) {
    return JSON.parse(json, (key, value) => {
        if (typeof value === 'string' && value.startsWith('function')) {
            return eval('(' + value + ')');
        }
        return value;
    });
}

// Assumed your Item class look like:
export class Item {
    constructor(text, func) {
        this.Text = text;
        this.Func = func;
    }
}

var list = [];
list[0] = new Item("text info", function func() {
    /* required code */
});

var listBak = decycleWithFuncs(list);
list = retrocycleWithFuncs(listBak);

console.log(list);
```

Edit: [See online -> TypeScript Playground ](https://www.typescriptlang.org/play/?module=1#code/PTAEGEFcGcBcHsC2oAmBTAxgTwwGzaAIYB2KoATmrOfNnmgFABmkxGsAlvMapjvgHUOsABYAxVhmgAKeACMAVgEpQAbwahNFKpHI8AUgGUA8gDkAdHHIdiAcw5MssxQBpQ0gNZosbgG6FcSDQVAF4APjUNLWiHd1gsAAc0eCZQf0CCEKzQAHIWNk5uHJV1aLKtSlhdHnSg8wRDahtbaSUAbijygF9OssrqtICgjuiu9oYe5klCnkqaOkFhcUkZBWhuEt7+vVAjM3MEwnJoNGk17jdPbz8h4NBwyPLNWOl4pJTBjPvsnKtmnNAADJAZ86nAjrBoEJRNI8tMuMRipsnn0dDs0OlYbDQABqUEEPHFYojJ49FHbGq3EmaMYdSZ4QjQaCgACSsDQyFKWgw3CskHY8HIrzQAA9YG58hhkU9RBxoOYACqi2D3UDssXUsqy+USNiqyWanqTfzkUC4OUqkKgADaAF0Oua4NaAAy21XENAAd1Z7MQ0gAROqVTYmPB-RL4dxQJLWo8tMAAFTaACOkA4lDIPPQoATwAm4wYJrNFoAQoQPKr0As0NDlmwZI7YONG6q5rR+DWlrqpNJG2WPAWecR1vhzLh4C1G+MgA)

**Comment by loglot** [comment]
> Try this one:
 
when using the TS playground you linked i ran it and got
```
[LOG]: [{
  "Text": "text info"
}]
```

**Comment by douglascrockford** [comment]
JSON does not include functions. Your 'should' statement is incorrect.
