### ISSUE TITLE
Would you consider releasing JSON-js under a permissive open source license instead of 'public domain'?

### ISSUE THREAD

**Issue by sgtdck** [douglascrockford/JSON-js#77]
I use [Winston](https://www.npmjs.com/package/winston) in my project, which relies on [cycle](https://www.npmjs.com/package/cycle) which is a fork of JSON-js. I would like to open source my project under Apache 2.0, but as JSON-js is explicitly declared as 'Public Domain', this poses problems.

Would you consider adding a permissive open source license (BSD, MIT, Apache, other)? I'd be happy to make a PR with the necessary changes.

Cheers

**Comment by douglascrockford** [comment]
If Public Domain is is not permissive enough for you, then I recommend that you write your own software.

**Comment by akuckartz** [comment]
@sgtdck There are no problems.

**Comment by sgtdck** [comment]
There [are](http://programmers.stackexchange.com/questions/148146/open-source-code-with-no-license-can-i-fork-it).

**Comment by akuckartz** [comment]
@sgtdck The question you linked to is about code which is **neither** Open Source nor Public Domain.

The accepted answer there correctly states:
> something is only "public domain" if it has either expired copyright (which mostly means it was written decades ago) or if the author has explicitly placed it in the public domain in writing.

All the js-files in this repository contain the statement "Public Domain" in a comment in the fifth line. That is enough to explicitly place them in the public domain.

**Comment by sgtdck** [comment]
Thanks for pointing that out @akuckartz , there seems to be no problem after all. Apologies for wasting both your time.

**Comment by mk-pmb** [comment]
Unfortunately, in my country, the artist protection laws don't allow public domain, so the act of granting permission that you implied by writing "Public domain." in your files, has no effect here, and the default of "all rights reserved" applies. Of the licenses I know, the one most closely representing public domain would be CC-0; 2nd-closest, but easier to read, would be ISC. Could you grant me/anyone those, additionally? e.g.

```diff
-//  Public Domain.
+//  Public Domain. Additional licenses granted (redundant in some countries): CC-0, ISC.
```

You can leave out the redundandy hint, it's just to avoid confusion for readers from countries where PD works. I was tempted to write it with an "if" clause, but that could be read as a condition that people must be able to prove in order to obtain those licenses.

**Comment by douglascrockford** [comment]
I share your understanding that you are not a lawyer.
